### PR TITLE
Added radix Sort

### PR DESCRIPTION
**Pull request by aswarth123**
Added radix sort and made changes to respective files.

### CODE REVIEW

**Comment by aswarth123** [comment]
What else is left here to do?

**Comment by LucasPilla** [comment]
The visualization is working amazingly! I saw that Radix Sort uses Counting Sort, is this a normal Counting Sort? , if yes can you reuse the one that i have already implemented?

**Comment by aswarth123** [comment]
Actually it has some difference I tried doing it that way but it was not working properly so made it again.

**Comment by LucasPilla** [comment]
Ok! For the radix sort is done, if you want to keep contribuiting, the main option is to implement new algorithms.
Thank you again for helping, all you did worked directly.

**Comment by aswarth123** [comment]
You didn't merge it

**Comment by aswarth123** [comment]
Thanks for support

**Comment by LucasPilla** [comment]
Just a detail, hahaha!

**Pull request merged**
