### PR TITLE
Compress Gifs

### PR DESCRIPTION
**Pull request by highb33kay**
@LucasPilla So this is how I synced the Gifs for #152 :

1. I determined how long the slowest Algo Gif (Selection Sort) ran for (1 : 10 : 08). 
2. I added a wait time to the other Gifs, So they wait for Selection Sort Gif to reach the finish line. 
3. I ran a test to ensure they synced. 
4. The Gifs are linked to Base Repo so I cant see changed in mine repo until merged. 

Tag hacktoberfest if merged. 😂

### CODE REVIEW

**Comment by LucasPilla** [comment]
@highb33kay Great! Can you share how you did it?
Is it possible to create just one gif with all algorithms synced?

**Comment by highb33kay** [comment]
Do you mean a one gif to rule then all situation? I mean all gifs will be merged into this one gif and will be synced to play.

**Comment by highb33kay** [comment]
I just researched with the knowledge that the gif is just a played media and found https://stackoverflow.com/questions/53509022/r-imagemagick-how-to-add-delay-after-each-loop-in-animation.

**Comment by LucasPilla** [comment]
Hi @highb33kay! Actually I think the visualization was better with the gifs not synced. 

I have another task to be done, the gifs are quite heavy so I want to optimize/compress them. 
I can assign this task to you, do you want?

**Comment by highb33kay** [comment]
Yes, I do. Assign away, sir. 😅

**Pull request closed without merging**
