### PR TITLE
updated "algortihms" (added bucketSort)

### PR DESCRIPTION
**Pull request by niharika11031997**

### CODE REVIEW

**Comment by LucasPilla** [comment]
The visualization is working, but there is something wrong with the sorting, can you try to fix that?
The problem happens at the end of the array:
image

**Comment by niharika11031997** [comment]
I thought that sort is correct , and I guess in handledrawing , something
is wrong.
I'll try to fix whatever the problem is
Thanks for reply

**Comment by LucasPilla** [comment]
I dont think the problem is with handledrawing() because its working well for other algorithms.
I printed the array after sorting, here are the last 10 bars:
[ ..., 389, 391, 391, 394, 395, 398, 399, 400, 10, 10]

**Comment by niharika11031997** [comment]
Ok so in the end there is some issue right?
I'll try to fix that
Thanks.

**Comment by niharika11031997** [comment]
hey i made changes to code, please check now, i think it's working fine now

**Comment by LucasPilla** [comment]
Its working well! Thank you for helping the project and feel free to heep contributing :)

**Comment by niharika11031997** [comment]
Thanks , happy to help

**Pull request merged**
