### PR TITLE
turned sorting functions into generators

### PR DESCRIPTION
**Pull request by mugulmd**
Sorting functions have become generators by simply replacing calls to handleDrawing by yield statements : this way their execution is still paused during the delay set by the user, the algorithm package is independent of the rest of the code, and there's only one event loop which is kept in the main function.
We use an iterator in the main function to capture the results of the yield statements, which are then used for drawing.

### CODE REVIEW

**Comment by GlacialBlaze** [comment]
@mugulmd

I have tested and found the following:
- If we stop halfway, the bars remain unsorted
- The start button does not change to a stop button when clicked
- The program seems to freeze when the delay slider is changed at the beginning
- The delay slider seems to have no effect when scrolled or slid while sorting

Please check the code again, perhaps there some areas the generator missed out, or something.

**Comment by mugulmd** [comment]
Okay I think it should work now : 
- the delay was working fine but I was using seconds instead of milliseconds so the program was not freezing, it was just a thousand times slower than expected ^^
- indeed I forgot to re-implement some play-pause-stop functionalities, but it should be fixed now (even the space bar pause during sorting)

**Comment by GlacialBlaze** [comment]
Good progress.

However, I found the following:
- On start, the visualizer has already green bars - it's supposed to be an empty white screen.
- When paused in the middle of sorting, the bars lose the blue and red colors which are the check and swap indicators.

Perhaps there might be a little adjustments here and there?

**Comment by mugulmd** [comment]
Done :)

**Comment by GlacialBlaze** [comment]
The visualizer seems to be free from error now - good job.

However, let us explore just a little bit on the button mechanism. This is not an error but I notice that the button is doing too much work, like having two states, and each state is constantly updated, and the switching off-and-on is rather complicated.

Can the way the button works be simplified? Perhaps a little change in the main loop or the update of the `ButtonBox`?

**Comment by mugulmd** [comment]
I agree with you but I don't see any "unnecessary" code :/
I think the main reason is that a 2 states button is a quite complex object, that does various actions and gets updated in various ways depending on the context, so you have to check the different configurations of this context. Moreover you have to code the different actions outside of the ButtonBox class because they are specific to this play-stop button.
It would probably be clearer and more efficient to create 2 buttons that only have 1 state (1 for play and 1 for stop), each one being able to execute only 1 action, and switching between them when they are clicked (which is what I did when writing the gui package).

As for code clarity we could just put the different actions executed when clicking the button inside separated functions and call these functions in the main loop (and maybe add some more comments).

However if you have a way to simplify things that I didn't see I'd be happy to hear it of course :)

**Comment by GlacialBlaze** [comment]
I see.

I'm interested in the '2 buttons thing (1 for play, the other for stop)' which you said you had implemented before.

Would it add way more lines of code? Is it too much of work to implement that?

**Comment by mugulmd** [comment]
I don't think so, I can try later today :)

**Comment by mugulmd** [comment]
I think it works just fine and the code is a bit more elegant indeed :)

**Comment by GlacialBlaze** [comment]
The play-stop mechanism looks simpler and better - good work.

Now, there's this thing I noticed: `variables.py`. Can those global variables be put in `display.py` to save an extra file and make consistent the variable directory (like all `display.`... rather than having an extra `variable.`...) in `main.py`?

**Comment by mugulmd** [comment]
Indeed this new file wasn't very useful ^^ 
I removed it and updated the code :)

**Comment by GlacialBlaze** [comment]
Our friend @rx112358 has created a vertical scrollbar on his side. I merged his pull request. @mugulmd Could you please update your code? The difference should be only in `display.py`, line 95 - 120 of the master branch.

**Comment by mugulmd** [comment]
Ok sorry for all the useless commits I was trying to solve the conflict locally but I found out you can do it directly on Github's interface and it's a lot easier ^^

**Comment by GlacialBlaze** [comment]
@mugulmd 
It's OK. Sorry to have you update it spontaneously. Great job!

@LucasPilla
Sorting functions no longer need to import `handleDrawing` as they are generators that simply yield results. Most of the actions are now compactly handled in the master loop in `main.py`. And some other minor improvements.

**Pull request merged**
