### PR TITLE
Added Bucket Sort

### PR DESCRIPTION
**Pull request by SaiSrichandra**
Hello @LucasPilla 
I have added the Bucket Sort algorithm in the algs.py file as per the instructions.
Please merge it with the master branch if found useful
Thank you

### CODE REVIEW

**Comment by LucasPilla** [comment]
Its not working

**Comment by SaiSrichandra** [comment]
What is the problem?
I have tested it using arbitrary values and it worked fine
Where was the problem

**Comment by LucasPilla** [comment]
I think I know the problem!
All the algorithms should sort the array *IN_PLACE*,  I mean not to create a array inside the algorithm and its not necessary to return anything! In your case when you empty the array it may be creating a local list and when the function is over the list is lost.

**Comment by SaiSrichandra** [comment]
Yeah that might explain it
I will try to do it in place or try to reference the actual array variable

**Comment by SaiSrichandra** [comment]
Can you please try it again

**Comment by LucasPilla** [comment]
The sorting is working, but when i access the array in main.py it is empty.

**Comment by LucasPilla** [comment]
I figured out that for some reason in line 31: '''array  = array + bucketList[x]''' the memory adress for array keeps alternating. I used the method .extend() to fix that.
The strangest part is that it keeps alternating between the same addresses:
0x522aa68
0x5212308
0x522aa68
0x5212308
...

**Comment by LucasPilla** [comment]
Thanks for helping me! If you have any algorithm in mind or intend to help somehow i 
appreciate!

**Comment by SaiSrichandra** [comment]
Yeah sure I will think about any other algorithms

By the way, I too couldn't understand why it keeps alternating

**Comment by SaiSrichandra** [comment]
Hey 
Can you add hacktoberfest-accepted label to this

**Pull request merged**
