### PR TITLE
added pancakesort

### PR DESCRIPTION
**Pull request by PedroDKE**
cool sorting algorithm, but visualisation could be better (choosing when to draw what colour, where) but okay

### CODE REVIEW

**Comment by PedroDKE** [comment]
also made the play button relative to the input box for now, (it was annoying for longer names). but solution will for now put every member of buttonbox at this specifi position so a cleaner solution might be required if more buttons get added

**Review by LucasPilla — APPROVED** [review]
I just changed the way to define button draw coordinates. I directly modify self.rect.x so the collision keeps aligned to the drawing

**Comment by LucasPilla** [comment]
How easy is to contribute to this project? It looks like you wrote this code yourself, because your pull requests works perfectly, i just have to merge them.

**Comment by PedroDKE** [comment]
well yeah, no major changes except adding a new file/algorithm or changing a single line untill now. Nothing github shouldnt be able to handle

**Pull request merged**
