### PR TITLE
Added bogosort algorithm

### PR DESCRIPTION
**Pull request by aewens**
In regards to issue:
#5 Implement a new Sorting Algorithm

### CODE REVIEW

**Comment by aewens** [comment]
I went ahead and fixed the merge conflicts on this.

**Comment by LucasPilla** [comment]
Can you rewrite in a clear way! I mean without copying the array, maybe remove unnecessary variables. You can use https://www.geeksforgeeks.org/bogosort-permutation-sort/ for reference, it doenst need to be separeted in multiple functions

**Comment by aewens** [comment]
Is this any clearer?

**Review by LucasPilla — APPROVED** [review]
Now its ok!

**Comment by LucasPilla** [comment]
Thanks for helping! If you intend to  implement others algorithms or help somehow you are welcome!

**Pull request merged**
