### PR TITLE
bitonicSort.py

### PR DESCRIPTION
**Pull request by shubhamnag14**
updated the __init__.py
and submitted the bitonicSort algorithm using python
as far the guidelines

### CODE REVIEW

**Comment by LucasPilla** [comment]
There is something strangely wrong, sorting result:
Can you try to fix that?
bitonicsort

**Comment by shubhamnag14** [comment]
okay...i will try to correct the algo

**Comment by LucasPilla** [comment]
@shubhamnag14 
Hey, i just want to check if you are still working in this algorithm, if so take your time :)

**Comment by shubhamnag14** [comment]
i am trying to solve the problem..but couldn't solve it..

**Comment by LucasPilla** [comment]
@shubhamnag14 I just merged the pull request from the other guy that implemented bitonic sort! I aprecciate the time you spent working on this, so I would like you to be listed as a contributor! If you find any issue that you feel comfortable working on just do it, otherwise I will manage something, if you want of course! ;)

**Pull request closed without merging**
