### PR TITLE
Add speed option (fixing issue #191)

### PR DESCRIPTION
**Pull request by Darius-ss10**
The execution speed can be changed using a slider. The user can either do a slide movement with its mouse to move the speed slider or simply click where he wants the slider to go. The speed range goes from 1 (slow = 1000ms delay) to 100 (fast = 10ms delay). 

Files changed :
- display.py : I've updated the already existing SlideBox
- main.py : I've added the SlideBox object and implemented the logic for the delay

### CODE REVIEW

**Comment by LucasPilla** [comment]
Fixes #191

**Review by LucasPilla — CHANGES_REQUESTED** [review]
Hey @Darius-ss10, well done!

Instead of using pygame.time.wait, which freezes the whole program, try the following:

```
if time()-timer_delay >= display.delay:
      numbers, redBar1, redBar2, blueBar1, blueBar2 = next(alg_iterator)
      display.drawInterface(numbers, redBar1, redBar2, blueBar1, blueBar2)
      timer_delay = time()
```

This way we stop just the sorting, but the program logic keeps working.
Can you change from "Speed" to "Delay", with the default value being 0 (no delay).

**Comment by Darius-ss10** [comment]
Hello @LucasPilla ! 

I've changed the way of how the delay was applied and now the implementation should normally respect your most recent request (a timer which doesn't freeze the whole display is used instead of pygame.time.wait). 

As you've requested, the default delay value is 0ms (which means the sort animation goes quite fast). The user can choose any delay value between 0 and 100ms.

**Comment by LucasPilla** [comment]
Hey @Darius-ss10, great job. I just did some minor changes
Thanks for collaborating 😄.

**Review by LucasPilla — APPROVED** [review]

**Pull request merged**
