### PR TITLE
Added Delay Scrolling

### PR DESCRIPTION
**Pull request by GlacialBlaze**
Now, you can adjust `delay` by scrolling your mouse (while it is hovering in the box) and also while its sorting the bars!

### CODE REVIEW

**Review by LucasPilla — APPROVED** [review]
Well done! :)

**Comment by LucasPilla** [comment]
@GlacialBlaze There is an pull request for changing delay with keys. Do you think it makes sense to have it?

**Comment by GlacialBlaze** [comment]
@LucasPilla 

Oh, I did not realize it. Will check it out, thanks.

**Comment by GlacialBlaze** [comment]
@LucasPilla

It makes sense because not everyone can scroll, like some have no mouse, some laptops have no scroll bar, and so on.

**Pull request merged**
