### PR TITLE
Added Pigeonhole Sorting Algorithm to Visualizer + fixed Bogosort freeze

### PR DESCRIPTION
**Pull request by bdanzig**
Pigeonhole sort is like counting sort, but instead of being in-place, it moves elements to individual buckets and pulls them out in sorted order. Let me know if you have any questions or concerns with the code! 

EDIT: I've also added a commit resolving issue #100.

### CODE REVIEW

**Review by LucasPilla — APPROVED** [review]

**Comment by LucasPilla** [comment]
@bdanzig Hey, thank you for contributting. Currently, some algorithms in this program does not heppens in place, 
what does not make sense visualizing them. I plan to remove some of them, this is why i wont be adding pigeonhole.

**Comment by LucasPilla** [comment]
@bdanzig Could you remove pigeonhole related files from these commits? Thanks in advance!

**Comment by GlacialBlaze** [comment]
@LucasPilla
I agree that sorts where most of the action happen in the auxiliary array do not make much of a visualization, however, for the sake of 'completeness', I suggest that we accept all sorts and put them in the `algorithms` folder, but we can choose not to display it by not importing it in the `algorithms.py` file. This way, everyone has freedom to run however they want. What do you think?

**Review by LucasPilla — APPROVED** [review]
Great! Thank you for contributting!

**Pull request merged**
